# adapted from https://towardsdatascience.com/pre-commit-hooks-you-must-know-ff247f5feb7e
# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.4.0
    hooks:
      - id: nbqa-black
        args: [-l80]
      - id: nbqa-pyupgrade
        args: [--py36-plus]
      - id: nbqa-isort
        args: [--profile=black, -l80]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "-l80"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [-l 80]
      - id: black-jupyter
        args: [-l 80]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "--disable=unexpected-keyword-arg",
            "--disable=no-value-for-parameter",
            "--disable=too-many-function-args",
            "--disable=missing-module-docstring",
            "--disable=wildcard-import",
            "--disable=abstract-method",
            "--disable=arguments-differ",
            "--disable=too-many-instance-attributes",
            "--disable=too-many-arguments",
            "--disable=invalid-name",
            "--disable=fixme",
          ]
